version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.watcher.enabled=false
      - xpack.security.enabled=false
    # mem_limit: 3g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  kibana1:
    image: docker.elastic.co/kibana/kibana:5.4.3
    environment:
      ELASTICSEARCH_URL:  http://elasticsearch1:9200
      # ELASTICSEARCH_USERNAME: elastic
      # ELASTICSEARCH_PASSWORD: changeme
      XPACK_SECURITY_ENABLED: "false"
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch1
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet: